pre-commit:
  jobs:
    - name: lint verification
      run: yarn --cwd code lint:staged

pre-push:
  jobs:
    - name: lint verification
      run: yarn --cwd code lint:staged
    - name: dependencies audit
      run: yarn --cwd code audit:prod
